"""Prepare the extended delivery-limit experiment from the validated snapshot engine."""
from pathlib import Path
p=Path(__file__).resolve().parent
s=(p/'run_laozhuang_snapshot_refinement.py').read_text(encoding='utf-8')
s=s.replace("PREVIOUS=CASE/'output/laozhuang_round2_refinement'","PREVIOUS=CASE/'output/laozhuang_gate_coefficient_trials/scale_1.05'")
s=s.replace("OUT=CASE/'output/laozhuang_snapshot_refinement'","OUT=CASE/'output/laozhuang_delivery_5pct'")
s=s.replace('INTERVAL=6;PREFIX=5;TIERS=[.3,.4,.5]','INTERVAL=6;PREFIX=5\nimport itertools\nTIERS=itertools.count(6)\nMU={\'Uef\':.63,\'Ues\':.63,\'Ucf\':.315,\'Ucs\':.84}')
s=s.replace("original_intervals=pd.read_csv(PREVIOUS/'refinement_intervals.csv')","original_intervals=pd.read_csv(CASE/'output/laozhuang_round2_refinement/refinement_intervals.csv')")
s=s.replace("print(f'High-depth failing intervals: {len(intervals)}; prefix {PREFIX}; caps {TIERS}',flush=True)","print(f'High-depth failing intervals: {len(intervals)}; prefix {PREFIX}; start 60%, +10 percentage points; execution threshold5%',flush=True)")
s=s.replace('  for cap in TIERS:','  plateau=0\n  for tier in TIERS:\n   cap=round(.6*1.5**(tier-6),10)')
s=s.replace("reason='execution_error_over_2pct' if execution>.02 else ('water_accuracy_passed' if local['passed'] else ('maximum_cap_reached' if cap==TIERS[-1] else 'continue'))","reason='execution_error_over_5pct' if execution>.05 else ('water_accuracy_passed' if local['passed'] else 'continue')")
s=s.replace("   else:\n    for item in active:\n     if item['status']=='active':item['status']='no_global_improvement'", "   else:\n    # Keep the best full-period branch but allow wider future search.\n    pass")
s=s.replace("   if accepted:\n    best=candidate", "   identical=(abs(candidate.q_command_m3s-best.q_command_m3s).max()<1e-8 and abs(candidate.h_sim_m-best.h_sim_m).max()<1e-8)\n   plateau=plateau+1 if identical else 0\n   if accepted:\n    best=candidate")
s=s.replace("   print(f'cap {cap:.0%} finished, accepted={accepted}, RMSE={score[\"RMSE_m\"]:.6f}',flush=True)","   print(f'cap {cap:.0%} finished, accepted={accepted}, RMSE={score[\"RMSE_m\"]:.6f}',flush=True)\n   (OUT/'progress.json').write_text(json.dumps({'history':history,'intervals':intervals},ensure_ascii=False,indent=2),encoding='utf-8')\n   best.to_csv(OUT/'best_so_far_audit.csv',index=False,encoding='utf-8-sig')\n   if plateau>=3:\n    for item in intervals:\n     if item['status']=='active':item['status']='search_plateau_without_5pct_execution_error'\n    break")
s=s.replace("PREVIOUS/'laozhuang_round2_boundaries.csv'","PREVIOUS/'fixed_boundaries.csv'")
s=s.replace("'flow_tiers':TIERS,","'flow_tiers':[entry['cap'] for entry in history],'execution_error_threshold':.05,")
s=s.replace('amplitude_cap=.5,','amplitude_cap=.6,')
s=s.replace('after_run=refine)','after_run=refine,gate_mu=MU)')
s=s.replace('start 60%, +10 percentage points','start 60%, range grows by factor1.5')
s=s.replace('  plateau=0\n','  plateau=0;has_accepted_snapshots=False\n')
s=s.replace("name=f'accepted_{checkpoint}' if history else f'periodic_{checkpoint}'", "name=f'accepted_{checkpoint}' if has_accepted_snapshots else f'periodic_{checkpoint}'")
s=s.replace('   rows=best.iloc[:checkpoint].to_dict(\'records\');trials=0','   rows=best.iloc[:checkpoint].to_dict(\'records\');trials=0;failed_probes=[]')
s=s.replace("      result=execute(k,q,opening,source);trials+=1\n      candidates.append", "      try:\n       result=execute(k,q,opening,source);trials+=1\n      except RuntimeError as error:\n       failed_probes.append({'cycle':k,'q':q,'error':str(error)})\n       continue\n      candidates.append")
s=s.replace("     if (candidates[0]", "     if not candidates:raise RuntimeError('no stable candidate at cycle '+str(k))\n     if (candidates[0]")
s=s.replace("     chosen_item=min(candidates", "     if not candidates:raise RuntimeError('no stable candidate at cycle '+str(k))\n     chosen_item=min(candidates")
s=s.replace("     if (candidates[0][3]['h_up']-target)*(candidates[-1][3]['h_up']-target)<=0 and hi>lo:","     if len(candidates)>1 and not any(x['cycle']==k for x in failed_probes) and (candidates[0][3]['h_up']-target)*(candidates[-1][3]['h_up']-target)<=0 and hi>lo:")
s=s.replace("'accepted':accepted,'intervals':trial_report}","'accepted':accepted,'intervals':trial_report,'failed_probes':failed_probes}")
s=s.replace("   identical=(abs(candidate.q_command_m3s-best.q_command_m3s).max()<1e-8 and abs(candidate.h_sim_m-best.h_sim_m).max()<1e-8)","   identical=bool(failed_probes) and all(x['flow_execution_mean_relative_error']<=.05 for x in trial_report)")
s=s.replace('    best=candidate\n','    best=candidate;has_accepted_snapshots=True\n')
# Probe the upper request through the whole changed control window, rather than
# claiming delivery limits from a water-fit optimizer that always avoids them.
s=s.replace('for q in sorted({lo,hi,qseed}):','for q in sorted({qseed,hi}):')
s=s.replace("chosen_item=min(candidates,key=lambda x:x[:2]);chosen=chosen_item[2];chosen_result=chosen_item[3]", "chosen_item=max(candidates,key=lambda x:x[2]);chosen=chosen_item[2];chosen_result=chosen_item[3]")
s=s.replace("     if len(candidates)>1 and not any(x['cycle']==k for x in failed_probes) and (candidates[0][3]['h_up']-target)*(candidates[-1][3]['h_up']-target)<=0 and hi>lo:", "     if False:")
s=s.replace("   candidate.to_csv(OUT/f'tier_{int(cap*100)}_audit.csv'", "   if any(x['flow_execution_mean_relative_error']>.05 for x in trial_report):accepted=False\n   candidate.to_csv(OUT/f'tier_{int(cap*100)}_audit.csv'")
(p/'run_laozhuang_delivery_5pct.py').write_text(s,encoding='utf-8')
plot=(p/'plot_laozhuang_snapshot_refinement.py').read_text(encoding='utf-8')
plot=plot.replace('output/laozhuang_snapshot_refinement','output/laozhuang_delivery_5pct')
plot=plot.replace('output/laozhuang_round2_refinement/reconstruction_audit.csv','output/laozhuang_gate_coefficient_trials/scale_1.05/reconstruction_audit.csv')
plot=plot.replace('此前局部精修','系数1.05倍原分水').replace('此前精修分水','扩大前分水')
plot=plot.replace('分水范围按原始流量30%、40%、50%递增；','分水范围从原始流量±60%开始，每档允许幅度乘1.5继续扩大；')
plot=plot.replace('平均有符号分水执行误差>2%','平均有符号分水执行误差>5%')
plot=plot.replace('最大50%仍未满足时记录到达上限，不宣称触发了执行能力限制。','不设置此前50%的上限；连续三档未改善时记录搜索平台，未达到5%不能宣称触发执行能力限制。')
plot=plot.replace('从此前第二轮控制值开始','固定上轮1.05倍过流系数，从对应控制值开始')
plot=plot.replace('此前第二轮|本次精修','扩大前|本次精修')
(p/'plot_laozhuang_delivery_5pct.py').write_text(plot,encoding='utf-8')
